### ISSUE TITLE
XSS漏洞

### ISSUE THREAD

**Issue by WowStarWorld** [xxtg666/xtGitVote#2]
在输入`投票标题`时，输入html代码未转义，存在非常严重的安全漏洞
如：
1. 在iframe srcdoc内使用script读取cookie中的accessToken
2. 使用script/meta导致页面跳转

解决办法：
1. 使用 `HTMLElement`.innerText改变文本
2. 使用`JQuery`.text函数改变文本
而不是使用`${文本}`

**Comment by xxtg666** [comment]
已修复
